apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-service
spec:
  selector:
    app: cats-dogs-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
